# Generated by Django 3.2.3 on 2021-06-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shedule',
        ),
    ]
