# Generated by Django 3.2.3 on 2021-05-24 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Вид доставки',
                'verbose_name_plural': 'Виды доставки',
                'db_table': 'delivery',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Вес')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Вес',
                'verbose_name_plural': 'Вес',
                'db_table': 'weight',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendersAddress', models.CharField(max_length=300, verbose_name='Адрес отправителя')),
                ('sendersPhone', models.CharField(max_length=15, verbose_name='Телефон отправителя')),
                ('sendersFio', models.CharField(max_length=100, verbose_name='ФИО отправителя')),
                ('recipientAddress', models.CharField(max_length=300, verbose_name='Адрес получателя')),
                ('recipientPhone', models.CharField(max_length=15, verbose_name='Телефон получателя')),
                ('recipientFio', models.CharField(max_length=100, verbose_name='ФИО получателя')),
                ('dateCreate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа')),
                ('dateReceive', models.DateTimeField(verbose_name='Дата получения')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Ценность')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.delivery', verbose_name='Вид доставки')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.payment', verbose_name='Способ оплаты')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.status', verbose_name='Статус')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('weight', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.weight', verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'managed': True,
            },
        ),
    ]
