# Generated by Django 3.2.3 on 2021-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_token',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
